### PR TITLE
Adding DevContainer support

### PR DESCRIPTION
**Pull request by panoramix360**
As promised on issue #95, we added support for DevContainer from Microsoft on Visual Code.

We added some steps on README to help others running the project and marked as optional.

### CODE REVIEW

**Comment by wmnnd** [comment]
Very cool, thanks for building this! :clap: 

I just gave it a try and I have a few thoughts:
- I needed to change the `docker-compose` file version to `"2"` to make it work on my machine. As far as I can see, it uses no features from 3.x
- It looks like the npm setup doesn’t quite work. When started the system for the first time, I needed to run `npm i` manually first, before it would work.
- The containers are all Debian-based and thus much larger than their Alpine counterparts. Changing this would probably require a fair bit of work, and I don’t know if it would be worth it. So I’d be happy to merge with the current setup :smiley:

**Comment by panoramix360** [comment]
Nice points @wmnnd, thank you for letting me know.

I'll look into it to discover why `npm install` was not runned and the other points about the docker-compose version and Alpine.

I'll let you know my conclusions :)

**Comment by panoramix360** [comment]
Hi @wmnnd, sorry for the delay in this change.

We are getting back from the holidays and will return our work here :D

**Comment by wmnnd** [comment]
No worries, I’m very happy you’re still motivated to help :partying_face:

**Comment by panoramix360** [comment]
@wmnnd we updated with what you suggested!

We included `mix deps.get` command on the postCreateCommand too, so after running devcontainer for the first time, the developer will only need to run `mix phx.server` :D

Please, let me known what you think

**Comment by wmnnd** [comment]
Looking great, thanks for this contribution, it’ll make it super easy for new people who want to contribute :heart:

**Pull request merged**
