### PR TITLE
Implement Templating System

### PR DESCRIPTION
**Pull request by wmnnd**
It’s finally here, templating in Keila!

Screenshot_2021-03-19 Open Source Newsletter Tool · Keila

Other than a brand-new templating system, this PR also introduces some small improvements, like consistent index pages and a feature to clone campaigns.

As always, feedback is super welcome :smiley:

### CODE REVIEW

**Comment by wmnnd** [comment]
Are we ready to send emails with custom templates? :partying_face:

**Review by Jcambass — COMMENTED** [review]
Looking good on first sight. Will give it a second more indepth look this week and test localy.

**Comment by wmnnd** [comment]
Did you get a chance to take another look, @Jcambass? :smiley:

**Comment by Jcambass** [comment]
@wmnnd Sadly not 🙈 And I probably won't have time this week either.

**Comment by wmnnd** [comment]
Okay, no worries, then I’ll create the new release and we’ll see if there are any bugs if someone reports them :smile:

**Pull request merged**
