### PR TITLE
Keila Core, Send Campaign Later

### PR DESCRIPTION
**Pull request by Jcambass**
This patch adds the core foundation to allow scheduling campaigns to be sent at a later time.

The original idea was to schedule a job for each scheduled campaign.
This PR takes a different approach and implements a periodic worker that checks for scheduled campaigns and sends them.
The reasoning, as well as a non-comprehensive list of pros and cons, can be found in https://github.com/pentacent/keila/issues/11.

**Oban Upgrade**
I also upgraded Oban to the latest stable version since there have been some breaking changes on how queues and cron jobs are configured and a DB migration.
It's probably easier to upgrade now than later when there is more adoption so I snaked this one in here.
See: https://hexdocs.pm/oban/2.4.3/changelog.html#2-4-3-2021-02-07

**UI**
This patch intentionally does not implement a UI for this feature yet.

### CODE REVIEW

**Review by wmnnd — CHANGES_REQUESTED** [review]
This time I really have only two very minor remarks for consistency/clarity:

1) I found the name `cluster` for the scheduling queue a little confusing.
2) The property for sent/delivered campaigns is `sent_at`, so `send_at` would make more sense than `deliver_at`. But in order to avoid any kind of confusion, maybe `scheduled_for` would be even nicer.

Other than that, once again a very nice PR!
One thing that I really enjoy about working with Elixir and Phoenix is exemplified here: You can build your application like you would build a library, the web interface is really a UI layer on top of that :smiley:

**Comment by Jcambass** [comment]
1. The idea behind `cluster` here is to have a queue where non critical jobs can be performed. As you wrote in the issue: it's not a massive problem if we're a bit late with sending a scheduled campaign and keeping `mailer` going is more important. Instead of adding one queue for every feature we add a shared queue like `cluster` can be used.

That bein said this idea mostly makes sense for things like Sidekiq where each worker process listens to a specific queue. With Oban that's not the case AFAIK and having many queues is not costly anymore (https://hexdocs.pm/oban/changelog.html#2-4-0-2021-01-26).
So if you can think of a good nane for this queue (and maybe size) we can change it.

**Comment by wmnnd** [comment]
Thanks! Maybe something plain like `scheduled_campaigns` would work? And we might actually try to go with a max concurrency of 1 for that, since they don’t really need to run in parallel, do they?

**Comment by Jcambass** [comment]
@wmnnd Do you want to go for that style of almost one queue per worker or should we add a queue for all CRON jobs like `periodic` we can start with 1 concurrency and increase it if we ever need more periodic worker (which ideally are always fast and just enqueue/task off other work).

**Comment by wmnnd** [comment]
How about we name it simply `cron` then, with concurrency 1, and if we ever find that’s not suitable, we can always change it to something more specific again :-)

**Comment by Jcambass** [comment]
@wmnnd Sure `cron` is fine as well, personally I opted for `periodic` over `cron` to not commit a wrong idea that the `queue` name of workers configured in the `cron` plugin needs to be `cron` as well. But if you favour it over `periodic` we can change it.

In regards to renaming the queue this would probably need to be done by adding a new queue in one release and then removing it in a second release (or providing enough instructions for users to do that) in order to not break other users installations, so if possible I wanted to choose a good name now :)

**Comment by wmnnd** [comment]
I think you’re right and `periodic` might also avoid confusion between the queue and the plugin :+1:

**Comment by Jcambass** [comment]
@wmnnd Changed to `periodic` again :)

**Review by wmnnd — APPROVED** [review]

**Comment by wmnnd** [comment]
Thank you once again for this PR! Do you also want to add the UI portion of this feature? Otherwise I’ll take care of it this week :smiley:

**Comment by Jcambass** [comment]
@wmnnd I have something started but it's not much yet and I don't think that I will be able to get to it this week so feel free to take it.

**Pull request merged**
